'use client';

import { memo, useCallback, useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  ArrowLeft, Copy, Check, Loader2, LogOut, Trophy, Crown, Info,
  Flame, WashingMachine, Blocks, Key, Brain, Keyboard, Fingerprint, Globe, Lock,
  Play,
} from 'lucide-react';

// Per-game lucide icon + accent color for the picker tiles. Mirrors
// getGameIcon/getGameColor from @/app/utils/gameIcons but avoids that
// module's @mdi dependency (which we don't otherwise need on this route).
const GAME_VISUAL: Record<GameType, { Icon: typeof Flame; color: string }> = {
  thermite: { Icon: Flame, color: 'text-orange-400' },
  lockpick: { Icon: Key, color: 'text-yellow-400' },
  laundromat: { Icon: WashingMachine, color: 'text-cyan-400' },
  pincracker: { Icon: Fingerprint, color: 'text-blue-400' },
  'roof-running': { Icon: Blocks, color: 'text-purple-400' },
  'word-memory': { Icon: Brain, color: 'text-pink-400' },
  chopping: { Icon: Keyboard, color: 'text-green-400' },
  'repair-kit': { Icon: Keyboard, color: 'text-red-400' },
};

// Per-game thumbnail (transparent PNG generated by scripts/capture-thumbnails.mjs).
// Used by the GamePicker so the room view echoes the home page card grid.
const GAME_THUMB: Record<GameType, string> = {
  thermite: '/puzzles/thermite.png?v=3',
  lockpick: '/puzzles/lockpick.png?v=3',
  laundromat: '/puzzles/laundromat.png?v=3',
  pincracker: '/puzzles/pincracker.png?v=3',
  'roof-running': '/puzzles/roof-running.png?v=3',
  'word-memory': '/puzzles/word-memory.png?v=3',
  chopping: '/puzzles/chopping.png?v=3',
  'repair-kit': '/puzzles/repair-kit.png?v=3',
};
import { useUser } from '@/app/contexts/UserContext';
import { useAblyChannel, type ChannelStatus, type PresenceMember } from '@/app/utils/useAblyChannel';
import { checkBeepPlayer, successPlayer } from '@/public/audio/AudioManager';
import PlayerAvatar from '@/app/components/PlayerAvatar';
import { EMOTES, EMOTE_BY_ID, EMOTE_THROTTLE_MS } from '@/app/lobby/emotes';
import { playEmoteSound } from '@/app/lobby/emoteSounds';
import EmoteImage from '@/app/lobby/EmoteImage';
import { generateMatchSeed } from '@/lib/lobby/seededRandom';
import { determineHost } from '@/lib/lobby/host';
import { isGhostEnabled } from '@/lib/lobby/ghostGames';
import type { LobbyMessage } from '@/lib/lobby/messages';
import type { GameType } from '@/interfaces/user';
import type { GameResult } from '@/app/game/types';
import { orbitron } from '@/app/fonts';
import {
  trackMatchStarted,
  trackMatchCompleted,
  trackMatchForfeited,
  trackMatchTimedOut,
} from '@/app/utils/gtm';
import MatchView from './MatchView';

// Games available for 1v1 (RepairKit excluded — real-time mechanic).
const ONEV_ONE_GAMES: { id: GameType; label: string }[] = [
  { id: 'thermite', label: 'Thermite' },
  { id: 'lockpick', label: 'Lockpick' },
  { id: 'laundromat', label: 'Laundromat' },
  { id: 'pincracker', label: 'Pin Cracker' },
  { id: 'roof-running', label: 'Roof Running' },
  { id: 'word-memory', label: 'Word Memory' },
  { id: 'chopping', label: 'Chopping' },
];

// Lobby lifetime — universal across all games.
const LOBBY_IDLE_MS = 5 * 60 * 1000;   // close lobby after 5 min of no matches
const LOBBY_WARN_MS = 60 * 1000;       // show warning toast last 60s
const MATCH_MAX_MS = 3 * 60 * 1000;    // cap any single match at 3 min → draw
const COUNTDOWN_MS = 3 * 1000;         // sync the start: both clients unblock at the same goAt

// Fire-and-forget durable counter (lib/lobby/stats). Independent of GA4/GTM
// so 1v1 usage is queryable from Mongo regardless of tag-manager config.
type LobbyStatEvent =
  | 'match_started' | 'match_completed' | 'match_forfeited'
  | 'match_timed_out' | 'lobby_created';
function recordLobbyStat(event: LobbyStatEvent, game?: GameType): void {
  void fetch('/api/lobby/stats', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ event, game }),
  }).catch(() => {});
}

interface LobbyClientProps {
  code: string;
}

export default function LobbyClient({ code }: LobbyClientProps) {
  const { user } = useUser();
  const router = useRouter();
  // Anonymous play: guests get a stable per-tab identity stored in
  // sessionStorage so a reload keeps them in the same lobby slot.
  const [guestId, setGuestId] = useState<string | null>(null);
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const stored = sessionStorage.getItem('lobbyGuestId');
    if (stored) {
      setGuestId(stored);
      return;
    }
    const fresh = `guest-${(typeof crypto !== 'undefined' && crypto.randomUUID
      ? crypto.randomUUID()
      : Math.random().toString(36).slice(2)
    ).slice(0, 8)}`;
    sessionStorage.setItem('lobbyGuestId', fresh);
    setGuestId(fresh);
  }, []);
  const effectiveClientId = user?.id ?? guestId;
  const effectiveDisplayName = user?.displayName
    ?? user?.username
    ?? (guestId ? `Guest ${guestId.slice(-4).toUpperCase()}` : 'Player');
  const [copied, setCopied] = useState(false);
  const [match, setMatch] = useState<{ game: GameType; seed: number } | null>(null);
  const [myResult, setMyResult] = useState<GameResult | null>(null);
  const [opponentResult, setOpponentResult] = useState<GameResult | null>(null);
  const [opponentInputs, setOpponentInputs] = useState<unknown[]>([]);
  const [matchStartTime, setMatchStartTime] = useState<number | null>(null);
  // My own timestamped input stream for the current match. The winner posts
  // this as a ghost (it has accurate per-input timing; the host only sees the
  // opponent's network-jittered stream). Reset at the start of every match.
  const myInputLogRef = useRef<{ t: number; input: unknown }[]>([]);
  const matchStartTimeRef = useRef<number | null>(null);
  useEffect(() => {
    matchStartTimeRef.current = matchStartTime;
  }, [matchStartTime]);
  const [matchExpired, setMatchExpired] = useState(false);
  const [lobbyLastActivity, setLobbyLastActivity] = useState(() => Date.now());
  const [now, setNow] = useState(() => Date.now());
  // Synced go-time in the host's Date.now() frame, shipped on match:start.
  // Both clients compare to their own Date.now() — same wall-clock fire if
  // their clocks are NTP-synced (typical for browsers). Display is driven by
  // per-second setTimeouts aligned to goAt so the digits tick exactly at
  // second boundaries instead of waiting on a stale 1Hz interval.
  const [goAt, setGoAt] = useState<number | null>(null);
  // Host-controlled per-lobby setting. Persists across matches in the same lobby.
  const [focusMode, setFocusMode] = useState(false);
  // Each match captures the focusMode the host had at start time, so a mid-match
  // toggle doesn't affect the in-progress game.
  const [matchFocusMode, setMatchFocusMode] = useState(false);
  // Canonical outcome — host derives once it has full info and broadcasts via
  // match:outcome; both ends render based on this state, no per-client flicker.
  const [outcome, setOutcome] = useState<{
    winnerClientId: string | null;
    reason: 'finished' | 'timeout';
  } | null>(null);
  // Recent emote per player — wiped after the emote's loopMs window so
  // the WebP doesn't visibly restart and the bubble fades on cue.
  const [emotes, setEmotes] = useState<
    Record<
      string,
      { primaryUrl: string; fallbackUrl: string; label: string; loopMs: number; key: number }
    >
  >({});
  const lastEmoteSentRef = useRef(0);
  // Which game (if any) the host is publishing to the public lobby browser.
  // Null = private; setting a GameType heartbeats the lobby and lists it
  // under that game. Picking the same game again clears it (unpublishes).
  const [publishGame, setPublishGame] = useState<GameType | null>(null);
  // Last few matches played in this lobby (in-memory; resets on reload).
  const [matchHistory, setMatchHistory] = useState<MatchHistoryEntry[]>([]);

  // Preload lobby audio cues once on mount.
  useEffect(() => {
    checkBeepPlayer.whenReady();
    successPlayer.whenReady();
  }, []);

  const showEmote = useCallback((emoteId: string, fromClientId: string) => {
    const def = EMOTE_BY_ID[emoteId];
    if (!def) return;
    const key = Date.now();
    setEmotes((prev) => ({
      ...prev,
      [fromClientId]: {
        // Triggered emote is always rendered animated; if the animated WebP
        // 404s for some reason we fall back to the Fluent 3D PNG.
        primaryUrl: def.animatedUrl,
        fallbackUrl: def.fallbackUrl,
        label: def.label,
        loopMs: def.loopMs,
        key,
      },
    }));
    // Sound for both sender (immediate gesture) and receiver. The shared
    // AudioContext is created lazily and resumes on first user interaction,
    // so a receiver who's already clicked anywhere will hear it.
    playEmoteSound(emoteId);
    setTimeout(() => {
      setEmotes((prev) => {
        if (prev[fromClientId]?.key !== key) return prev;
        const next = { ...prev };
        delete next[fromClientId];
        return next;
      });
    }, def.loopMs);
  }, []);

  const handleMessage = useCallback((msg: LobbyMessage) => {
    if (msg.type === 'match:start') {
      setMatch({ game: msg.game, seed: msg.seed });
      setMyResult(null);
      setOpponentResult(null);
      setOpponentInputs([]);
      myInputLogRef.current = [];
      setMatchExpired(false);
      setMatchFocusMode(msg.focusMode);
      setOutcome(null);
      // Use the host's goAt. Cap to a sane local range so a wildly-skewed
      // peer clock can't make the countdown last minutes or fire instantly.
      const receiveNow = Date.now();
      const cappedGoAt = Math.min(
        Math.max(msg.goAt, receiveNow + 500),
        receiveNow + COUNTDOWN_MS + 1500,
      );
      // Sync `now` atomically so the first countdown render isn't off by
      // however stale the 1Hz interval state happened to be.
      setNow(receiveNow);
      setGoAt(cappedGoAt);
      // Match timer starts counting from GO, not from when match:start arrived.
      setMatchStartTime(cappedGoAt);
    } else if (msg.type === 'match:result') {
      setOpponentResult({ won: msg.won, score: msg.score, elapsedMs: msg.elapsedMs });
    } else if (msg.type === 'match:input') {
      setOpponentInputs((prev) => [...prev, msg.input]);
    } else if (msg.type === 'match:timeout') {
      setMatchExpired(true);
    } else if (msg.type === 'match:outcome') {
      setOutcome({ winnerClientId: msg.winnerClientId, reason: msg.reason });
    } else if (msg.type === 'emote') {
      showEmote(msg.emote, msg.fromClientId);
    }
    // 'suggest' messages from older clients are ignored — the guest no
    // longer has a suggest picker. Host's game pick is the single source
    // of truth.
  }, [showEmote]);

  const { status, presence, publish } = useAblyChannel<LobbyMessage>({
    channelName: `lobby:${code}`,
    presenceData: {
      displayName: effectiveDisplayName,
      discordId: user?.discordId,
      avatarHash: user?.avatar,
    },
    onMessage: handleMessage,
    enabled: !!effectiveClientId,
    clientId: effectiveClientId ?? undefined,
  });

  const hostClientId = determineHost(presence);
  const isHost = hostClientId !== undefined && hostClientId === effectiveClientId;
  const me = presence.find((p) => p.clientId === effectiveClientId) ?? null;
  const opponent = presence.find((p) => p.clientId !== effectiveClientId) ?? null;
  const opponentClientId = opponent?.clientId ?? null;

  // 1Hz ticker — drives all the countdown displays + expiry checks below.
  useEffect(() => {
    const interval = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(interval);
  }, []);

  // Only a new joiner counts as activity. If the opponent gets idle-kicked
  // first, the host's presence drops 2→1; we don't want that to reset the
  // host's own idle clock and let them sit forever.
  // Plays a subtle audio cue when the opponent first joins so the host
  // notices without having to watch the lobby tab.
  const prevPresenceLenRef = useRef(0);
  useEffect(() => {
    if (presence.length > prevPresenceLenRef.current) {
      setLobbyLastActivity(Date.now());
      if (prevPresenceLenRef.current > 0) {
        // Skip on initial 0→1 (that's just us mounting); fire when a peer joins.
        checkBeepPlayer.play();
      }
    }
    prevPresenceLenRef.current = presence.length;
  }, [presence.length]);

  // Audio: success sound when an opponent's result arrives (they finished
  // their game) so we know to look up. Skips on every other state change.
  const prevOpponentResultRef = useRef<GameResult | null>(null);
  useEffect(() => {
    if (opponentResult && !prevOpponentResultRef.current) {
      checkBeepPlayer.play();
    }
    prevOpponentResultRef.current = opponentResult;
  }, [opponentResult]);

  // Audio: success chime exactly at GO when the match unblocks.
  useEffect(() => {
    if (!goAt) return;
    const delay = goAt - Date.now();
    if (delay <= 0) {
      successPlayer.play();
      return;
    }
    const handle = setTimeout(() => successPlayer.play(), delay);
    return () => clearTimeout(handle);
  }, [goAt]);

  // When a match ends (back to lobby), reset activity so the next idle window
  // starts fresh.
  useEffect(() => {
    if (!match && !matchStartTime) return;
    if (match && (myResult || opponentResult || matchExpired)) {
      setLobbyLastActivity(Date.now());
    }
  }, [match, matchStartTime, myResult, opponentResult, matchExpired]);

  // Idle-lobby timeout: schedule a setTimeout aligned to the deadline rather
  // than polling `now` each tick. Polling could quietly miss firing if the
  // 1Hz interval was throttled (background tab) or out of phase; setTimeout
  // fires once at the right moment. Skipped only while a match is actively
  // running — the outcome view and pre-match countdown count toward idle.
  const isInActiveMatch = !!(match && !myResult && !opponentResult && !matchExpired);
  useEffect(() => {
    if (isInActiveMatch) return;
    const delay = lobbyLastActivity + LOBBY_IDLE_MS - Date.now();
    if (delay <= 0) {
      router.push('/lobby');
      return;
    }
    const handle = setTimeout(() => router.push('/lobby'), delay);
    return () => clearTimeout(handle);
  }, [isInActiveMatch, lobbyLastActivity, router]);

  // Schedule a re-render at each second boundary of the countdown, all
  // anchored on goAt. Without this the 1Hz interval fires at whatever phase
  // it landed on at lobby-mount, so the "1" digit might only flash for a
  // few hundred ms before the match starts.
  useEffect(() => {
    if (!goAt) return;
    const handles: ReturnType<typeof setTimeout>[] = [];
    for (let target = goAt - 2000; target <= goAt; target += 1000) {
      const delay = Math.max(0, target - Date.now());
      handles.push(setTimeout(() => setNow(Date.now()), delay));
    }
    return () => handles.forEach(clearTimeout);
  }, [goAt]);

  // Match max-duration: also setTimeout-based so it can't be missed by a
  // throttled tick. First client to expire publishes match:timeout so both
  // converge on a draw without UI flicker. Guards prevent firing after the
  // match is already resolved (e.g., opponent forfeited at 2:30 and the
  // timer would otherwise still flip the outcome to a fake draw at 3:00).
  useEffect(() => {
    if (!match || matchStartTime === null || matchExpired) return;
    if (myResult || opponentResult) return;
    const fire = () => {
      setMatchExpired(true);
      trackMatchTimedOut({ lobby_code: code, game_type: match.game });
      void publish({ type: 'match:timeout' });
    };
    const delay = matchStartTime + MATCH_MAX_MS - Date.now();
    if (delay <= 0) {
      fire();
      return;
    }
    const handle = setTimeout(fire, delay);
    return () => clearTimeout(handle);
  }, [match, matchStartTime, matchExpired, myResult, opponentResult, code, publish]);

  // Host arbiter: derive and broadcast the canonical match:outcome once we
  // have enough info. If only one side has a result yet, wait briefly for
  // the other before locking in.
  useEffect(() => {
    if (!isHost || outcome || !effectiveClientId || !opponentClientId) return;
    if (!myResult && !opponentResult && !matchExpired) return;

    const decide = () =>
      deriveWinner(myResult, opponentResult, matchExpired, effectiveClientId, opponentClientId);

    const publishAndSet = (decision: ReturnType<typeof deriveWinner>) => {
      void publish({
        type: 'match:outcome',
        winnerClientId: decision.winnerClientId,
        reason: decision.reason,
      });
      setOutcome(decision);
      if (match) {
        trackMatchCompleted({
          lobby_code: code,
          game_type: match.game,
          reason: decision.reason,
          has_winner: decision.winnerClientId !== null,
          duration_ms: matchStartTime ? Date.now() - matchStartTime : 0,
        });
      }
    };

    // Both results in hand (or matchExpired) — decide immediately.
    if ((myResult && opponentResult) || matchExpired) {
      publishAndSet(decide());
      return;
    }

    // Only one side reported. Give the other ~600ms to land before locking.
    const handle = setTimeout(() => publishAndSet(decide()), 600);
    return () => clearTimeout(handle);
  }, [isHost, myResult, opponentResult, matchExpired, outcome, effectiveClientId, opponentClientId, publish, code, match, matchStartTime]);

  // Append to match history once the canonical outcome lands, deduped by
  // match.seed so multiple effect runs don't push the same row twice.
  useEffect(() => {
    if (!outcome || !match) return;
    setMatchHistory((prev) => {
      if (prev.some((e) => e.seed === match.seed)) return prev;
      const winner = outcome.winnerClientId
        ? presence.find((p) => p.clientId === outcome.winnerClientId)
        : null;
      const entry: MatchHistoryEntry = {
        seed: match.seed,
        game: match.game,
        winnerClientId: outcome.winnerClientId,
        winnerName: winner?.data.displayName,
        winnerDiscordId: winner?.data.discordId,
        winnerAvatarHash: winner?.data.avatarHash,
        durationMs: matchStartTime ? Date.now() - matchStartTime : 0,
        endedAt: Date.now(),
      };
      return [entry, ...prev].slice(0, 5);
    });
  }, [outcome, match, presence, matchStartTime]);

  // Persist the finished match — once per seed, host only — to:
  //   1. recentMatches  → the public "live activity" ticker on /lobby
  //   2. lobbyStats      → the durable all-time counter (source of truth)
  // Both are best-effort and fire from the host so each match counts once.
  const recordedSeedsRef = useRef<Set<number>>(new Set());
  useEffect(() => {
    if (!outcome || !match || !isHost) return;
    if (recordedSeedsRef.current.has(match.seed)) return;
    recordedSeedsRef.current.add(match.seed);

    const winner = outcome.winnerClientId
      ? presence.find((p) => p.clientId === outcome.winnerClientId)
      : null;
    const loser = outcome.winnerClientId
      ? presence.find((p) => p.clientId !== outcome.winnerClientId)
      : null;

    void fetch('/api/lobby/recent-matches', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        game: match.game,
        winnerName: winner?.data.displayName ?? null,
        winnerDiscordId: winner?.data.discordId,
        winnerAvatarHash: winner?.data.avatarHash,
        opponentName: loser?.data.displayName ?? null,
        durationMs: matchStartTime ? Date.now() - matchStartTime : 0,
      }),
    }).catch(() => {});

    void recordLobbyStat(
      outcome.reason === 'timeout' ? 'match_timed_out' : 'match_completed',
      match.game,
    );
  }, [outcome, match, isHost, presence, matchStartTime]);

  // Harvest a ghost — winner-only, recorded by the WINNER's own client (it
  // holds the accurately-timed input log). Conditions: I won, the match
  // actually finished (not a timeout/forfeit), my result says won, and I have
  // a sane number of recorded inputs. Deduped per seed. Best-effort; this is
  // what fills the async-race pool. See docs/async-ghost-spec.md.
  const ghostRecordedSeedsRef = useRef<Set<number>>(new Set());
  useEffect(() => {
    if (!outcome || !match || !effectiveClientId) return;
    // Only harvest from games whose replay is verified for ghost racing.
    if (!isGhostEnabled(match.game)) return;
    if (ghostRecordedSeedsRef.current.has(match.seed)) return;
    const iWon = outcome.winnerClientId === effectiveClientId;
    if (!iWon || outcome.reason !== 'finished') return;
    if (!myResult?.won) return; // my own engine confirms a genuine completion
    const inputs = myInputLogRef.current;
    if (inputs.length < 2) return; // too few moves — skip degenerate runs
    ghostRecordedSeedsRef.current.add(match.seed);

    const me = presence.find((p) => p.clientId === effectiveClientId);
    void fetch('/api/lobby/ghosts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        game: match.game,
        seed: match.seed,
        inputs,
        result: myResult,
        recorderName: me?.data.displayName ?? effectiveDisplayName,
        recorderDiscordId: me?.data.discordId,
        recorderAvatarHash: me?.data.avatarHash,
        recorderClientId: effectiveClientId,
      }),
    }).catch(() => {});
  }, [outcome, match, effectiveClientId, myResult, presence, effectiveDisplayName]);

  // Non-host fallback: if the host's match:outcome doesn't arrive within a
  // couple of seconds (host disconnected mid-match), derive locally so the
  // outcome view still renders.
  useEffect(() => {
    if (isHost || outcome || !effectiveClientId || !opponentClientId) return;
    if (!myResult && !opponentResult && !matchExpired) return;

    const handle = setTimeout(() => {
      setOutcome(deriveWinner(myResult, opponentResult, matchExpired, effectiveClientId, opponentClientId));
    }, 2500);
    return () => clearTimeout(handle);
  }, [isHost, myResult, opponentResult, matchExpired, outcome, effectiveClientId, opponentClientId]);

  // Auto-resolve: if the opponent disconnects mid-match (closed tab, network
  // drop with no quick reconnect), give the win to the remaining player after
  // a short grace window. Covers brief flickers without ending early.
  useEffect(() => {
    if (!match || outcome || !effectiveClientId) return;
    if (presence.length >= 2) return;
    const handle = setTimeout(() => {
      const decision = { winnerClientId: effectiveClientId, reason: 'finished' as const };
      void publish({
        type: 'match:outcome',
        winnerClientId: decision.winnerClientId,
        reason: decision.reason,
      });
      setOutcome(decision);
      if (match) {
        trackMatchCompleted({
          lobby_code: code,
          game_type: match.game,
          reason: 'finished',
          has_winner: true,
          duration_ms: matchStartTime ? Date.now() - matchStartTime : 0,
        });
      }
    }, 3500);
    return () => clearTimeout(handle);
  }, [match, outcome, presence.length, effectiveClientId, publish, code, matchStartTime]);

  // 3rd-player kick: presence dedupes by clientId, but a public lobby could
  // race two joiners filling it past 2. Sort by Ably timestamp so every
  // client agrees on who arrived first; if I'm the 3rd, bounce back to the
  // lobby browser.
  useEffect(() => {
    if (presence.length < 3 || !effectiveClientId) return;
    const sorted = [...presence].sort((a, b) => a.timestamp - b.timestamp);
    const myIdx = sorted.findIndex((p) => p.clientId === effectiveClientId);
    if (myIdx >= 2) {
      router.replace('/lobby?full=1');
    }
  }, [presence, effectiveClientId, router]);

  // Public lobby heartbeat. Only the host pings — and only when logged in,
  // since the API requires a real session. The lobby is "published" iff
  // the host has picked a publishGame; that pick is the game label the
  // listing shows + filters by. The DB entry expires 90s after the last
  // ping so closing the tab / clearing publishGame frees the slot.
  const isLoggedInHost = isHost && !!user?.id;
  useEffect(() => {
    if (!publishGame || !isLoggedInHost) return;
    let cancelled = false;
    const ping = async () => {
      try {
        await fetch('/api/lobby/public', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            code,
            playerCount: presence.length,
            suggestedGame: publishGame,
          }),
        });
      } catch {
        // Heartbeat is best-effort — a missed ping just shortens the
        // listing's TTL by one cycle.
      }
    };
    void ping();
    // 15s heartbeat (TTL is 45s) so the listing stays alive while the host
    // is here but expires quickly once they leave.
    const interval = setInterval(() => {
      if (!cancelled) void ping();
    }, 15_000);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [publishGame, isLoggedInHost, code, presence.length]);

  // Explicit unregister when host clears publishGame or unmounts. The TTL
  // would clean up eventually, but firing the DELETE removes the listing
  // immediately so other browsers see the change on next refresh.
  const wasPublishedRef = useRef(false);
  // Mirror the live host/code into refs so the unmount cleanup below (which
  // runs with an empty dep array) sees the *current* values, not the ones
  // captured at mount — at mount isLoggedInHost is still false, so without
  // this a host who closes the tab while public never unlists the lobby and
  // it lingers in the pool the full TTL.
  const isLoggedInHostRef = useRef(isLoggedInHost);
  const codeRef = useRef(code);
  useEffect(() => {
    isLoggedInHostRef.current = isLoggedInHost;
    codeRef.current = code;
  }, [isLoggedInHost, code]);

  useEffect(() => {
    if (publishGame) {
      wasPublishedRef.current = true;
      return;
    }
    if (!wasPublishedRef.current || !isLoggedInHost) return;
    wasPublishedRef.current = false;
    void fetch(`/api/lobby/public/${code}`, { method: 'DELETE' }).catch(() => {});
  }, [publishGame, isLoggedInHost, code]);
  useEffect(() => {
    return () => {
      if (wasPublishedRef.current && isLoggedInHostRef.current) {
        void fetch(`/api/lobby/public/${codeRef.current}`, { method: 'DELETE' }).catch(() => {});
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);


  const handleCopy = async () => {
    if (typeof window === 'undefined') return;
    try {
      // Copy the full invite URL (not just the code) so a paste is a
      // one-click join for whoever receives it.
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Silent fail.
    }
  };


  const handleStart = async (game: GameType) => {
    const seed = generateMatchSeed();
    const startNow = Date.now();
    const newGoAt = startNow + COUNTDOWN_MS;
    setMatch({ game, seed });
    setMyResult(null);
    setOpponentResult(null);
    setOpponentInputs([]);
    myInputLogRef.current = [];
    setMatchExpired(false);
    setMatchFocusMode(focusMode);
    setOutcome(null);
    // Sync `now` atomically with goAt so the initial countdown render shows
    // exactly 3 instead of 4 (the 1Hz interval state can be up to 1s stale).
    setNow(startNow);
    setGoAt(newGoAt);
    setMatchStartTime(newGoAt);
    trackMatchStarted({ lobby_code: code, game_type: game, focus_mode: focusMode });
    recordLobbyStat('match_started', game);
    await publish({
      type: 'match:start',
      game,
      seed,
      startedAt: startNow,
      goAt: newGoAt,
      focusMode,
    });
  };

  const handleMatchEnd = useCallback(
    (result: GameResult) => {
      setMyResult(result);
      void publish({
        type: 'match:result',
        won: result.won,
        score: result.score,
        elapsedMs: result.elapsedMs,
      });
    },
    [publish],
  );

  const handleInput = useCallback(
    (input: unknown) => {
      // Log my own input with a timestamp relative to match start, so if I win
      // this run can be replayed as a ghost at its true cadence (capped at
      // MAX so a pathological run can't grow unbounded).
      const start = matchStartTimeRef.current;
      if (start !== null && myInputLogRef.current.length < 5000) {
        myInputLogRef.current.push({ t: Math.max(0, Date.now() - start), input });
      }
      void publish({ type: 'match:input', input });
    },
    [publish],
  );

  const handleForfeit = useCallback(() => {
    if (myResult) return;
    const elapsedMs = matchStartTime ? Date.now() - matchStartTime : 0;
    const result: GameResult = { won: false, score: 0, elapsedMs };
    setMyResult(result);
    if (match) {
      trackMatchForfeited({ lobby_code: code, game_type: match.game, duration_ms: elapsedMs });
    }
    void publish({ type: 'match:result', won: false, score: 0, elapsedMs });
  }, [myResult, matchStartTime, match, code, publish]);

  const handleBackToLobby = () => {
    setMatch(null);
    setMyResult(null);
    setOpponentResult(null);
    setOpponentInputs([]);
    setMatchExpired(false);
    setMatchStartTime(null);
    setGoAt(null);
    setOutcome(null);
    setLobbyLastActivity(Date.now());
  };

  const sendEmote = useCallback(
    (emoteId: string) => {
      const nowMs = Date.now();
      if (nowMs - lastEmoteSentRef.current < EMOTE_THROTTLE_MS) return;
      if (!effectiveClientId) return;
      lastEmoteSentRef.current = nowMs;
      // Show on my own side immediately (echo is disabled — we won't get our
      // own message back). showEmote also plays the sound.
      showEmote(emoteId, effectiveClientId);
      void publish({ type: 'emote', emote: emoteId, fromClientId: effectiveClientId });
    },
    [effectiveClientId, publish, showEmote],
  );

  // Synced countdown: rendered before anything else so neither client can
  // start playing before goAt.
  if (match && goAt && now < goAt) {
    return <Countdown remainingMs={goAt - now} />;
  }

  // Outcome view: only when the canonical outcome is in. Until then (between
  // a partial result landing and the host's match:outcome arriving) we keep
  // the game on-screen so the user isn't briefly shown the wrong winner.
  if (match && outcome) {
    const iWon = outcome.winnerClientId === effectiveClientId;
    const isDraw = outcome.winnerClientId === null;
    return (
      <>
        <OutcomeView
          iWon={iWon}
          isDraw={isDraw}
          reason={outcome.reason}
          game={match.game}
          winnerClientId={outcome.winnerClientId}
          myResult={myResult}
          opponentResult={opponentResult}
          me={me}
          opponent={opponent}
          emotes={emotes}
          onBack={handleBackToLobby}
        />
        {presence.length >= 2 && (
          <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40">
            <EmoteBar onSend={sendEmote} />
          </div>
        )}
      </>
    );
  }

  // Match in progress.
  if (match) {
    const matchRemainingMs =
      matchStartTime !== null ? Math.max(0, matchStartTime + MATCH_MAX_MS - now) : MATCH_MAX_MS;
    return (
      <>
        <MatchHeader remainingMs={matchRemainingMs} onForfeit={handleForfeit} />
        <MatchView
          game={match.game}
          seed={match.seed}
          onMatchEnd={handleMatchEnd}
          onInput={handleInput}
          opponentInputs={opponentInputs}
          focusMode={matchFocusMode}
          me={me}
          opponent={opponent}
          emotes={emotes}
        />
        <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40">
          <EmoteBar onSend={sendEmote} />
        </div>
      </>
    );
  }

  // Lobby view.
  const lobbyRemainingMs = Math.max(0, lobbyLastActivity + LOBBY_IDLE_MS - now);
  const showIdleWarning = lobbyRemainingMs <= LOBBY_WARN_MS;
  const meMember = presence.find((p) => p.clientId === effectiveClientId) ?? null;
  const opponentMember = presence.find((p) => p.clientId !== effectiveClientId) ?? null;

  return (
    <main className="relative min-h-screen flex flex-col bg-gradient-to-br from-mirage-950 via-mirage-900 to-mirage-950">
      <LobbyBackdrop />

      <div className="relative z-10 w-full max-w-3xl mx-auto px-4 sm:px-6 pt-6 pb-32">
        {/* Top utility row — 3-column grid so the code chip is dead-centre
            regardless of how wide the Leave / status sides are. */}
        <div className="grid grid-cols-3 items-center gap-3 mb-12">
          <div className="justify-self-start">
            <Link
              href="/lobby"
              className="group inline-flex items-center gap-2 text-gray-400 hover:text-spring-green-300 text-sm font-medium transition-colors"
            >
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              Leave
            </Link>
          </div>

          <div className="justify-self-center">
            <CodeChip code={code} copied={copied} onCopy={handleCopy} />
          </div>

          <div className="justify-self-end">
            <ConnectionStatus status={status} />
          </div>
        </div>

        {/* Players — the head-to-head hero */}
        <section className="mb-12">
          {status === 'failed' ? (
            <div className="rounded-lg bg-error-500/[0.06] border border-error-500/30 px-5 py-6 text-center">
              <p className="text-error-300 text-sm font-medium mb-1">
                Couldn&apos;t connect to the lobby
              </p>
              <p className="text-gray-400 text-xs mb-4">
                The realtime connection failed. Check your network and try again.
              </p>
              <button
                type="button"
                onClick={() => window.location.reload()}
                className="inline-flex items-center gap-1.5 rounded-lg bg-white/[0.04] hover:bg-white/[0.08] border border-white/10 hover:border-spring-green-400/40 text-white/90 hover:text-spring-green-300 px-4 py-2 text-sm font-semibold transition-all"
              >
                Retry
              </button>
            </div>
          ) : presence.length === 0 ? (
            <div className="py-12 text-center">
              <Loader2 className="w-5 h-5 animate-spin text-spring-green-400/40 mx-auto mb-3" />
              <p className="text-gray-500 text-xs font-mono">connecting to lobby…</p>
            </div>
          ) : (
            <PlayersVs
              me={meMember}
              opponent={opponentMember}
              hostClientId={hostClientId}
              emotes={emotes}
            />
          )}
        </section>

        {/* Host gets the game picker; the guest waits. */}
        {isHost ? (
          <GamePicker
            isAlone={presence.length < 2}
            publishGame={publishGame}
            onPublishChange={setPublishGame}
            onStart={handleStart}
            focusMode={focusMode}
            onFocusModeChange={setFocusMode}
            loggedIn={!!user?.id}
          />
        ) : presence.length >= 2 ? (
          <div className="rounded-lg bg-mirage-900/40 border border-white/[0.08] px-5 py-5 flex items-center gap-3">
            <Loader2 className="w-4 h-4 text-spring-green-400/50 animate-spin shrink-0" />
            <div className="text-gray-300 text-sm">
              Waiting for the host to pick a game…
            </div>
          </div>
        ) : null}

        {matchHistory.length > 0 && (
          <section className="mt-8">
            <div className="flex items-center gap-3 mb-4">
              <h2 className="text-sm font-bold bg-gradient-to-r from-spring-green-400 to-aquamarine-400 bg-clip-text text-transparent">
                Recent matches
              </h2>
              <span className="flex-1 h-px bg-gradient-to-r from-spring-green-500/20 to-transparent" />
            </div>
            <ul className="space-y-1.5">
              {matchHistory.map((entry) => (
                <MatchHistoryRow key={entry.seed} entry={entry} />
              ))}
            </ul>
          </section>
        )}
      </div>

      {/* Floating emote bar — visible in the lobby and outcome views. */}
      {presence.length >= 2 && (
        <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40">
          <EmoteBar onSend={sendEmote} />
        </div>
      )}

      {showIdleWarning && (
        <div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-50 px-4 py-2.5 rounded-full bg-amber-500/15 backdrop-blur-md border border-amber-500/35 text-amber-200 text-xs shadow-2xl shadow-amber-500/10 inline-flex items-center gap-2 tabular-nums">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
          Lobby closes in {Math.ceil(lobbyRemainingMs / 1000)}s
        </div>
      )}
    </main>
  );
}

/* Backdrop — mirrors the home page: faint green grid + soft ambient
   glow blobs over the mirage gradient. Keeps the room visually
   continuous with the rest of the site. */
function LobbyBackdrop() {
  return (
    <>
      <div className="fixed inset-0 opacity-10 pointer-events-none" aria-hidden="true">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: `
              linear-gradient(rgba(9, 222, 110, 0.1) 1px, transparent 1px),
              linear-gradient(90deg, rgba(9, 222, 110, 0.1) 1px, transparent 1px)
            `,
            backgroundSize: '50px 50px',
          }}
        />
      </div>
      <div className="fixed inset-0 overflow-hidden pointer-events-none opacity-20" aria-hidden="true">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-spring-green-500/10 rounded-full blur-2xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-aquamarine-500/10 rounded-full blur-2xl" />
      </div>
    </>
  );
}

/* Compact lobby-code chip — sits in the top bar. Click the code or the
   icon to copy; the second icon shares the room URL. */
// Single button: shows the lobby code, click copies the full invite URL.
function CodeChip({
  code,
  copied,
  onCopy,
}: {
  code: string;
  copied: boolean;
  onCopy: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onCopy}
      title="Copy invite link"
      className="group inline-flex items-center gap-2.5 rounded-lg bg-mirage-900/60 border border-spring-green-500/20 hover:border-spring-green-400/50 px-4 py-2 transition-colors"
    >
      <span
        className={`${orbitron.className} text-base font-black tracking-[0.2em] text-white`}
      >
        {code}
      </span>
      {copied ? (
        <span className="inline-flex items-center gap-1 text-spring-green-400 text-xs font-medium">
          <Check className="w-3.5 h-3.5" />
          Copied
        </span>
      ) : (
        <Copy className="w-3.5 h-3.5 text-gray-400 group-hover:text-spring-green-300 transition-colors" />
      )}
    </button>
  );
}

interface MatchHistoryEntry {
  seed: number;
  game: GameType;
  winnerClientId: string | null;
  winnerName?: string;
  winnerDiscordId?: string;
  winnerAvatarHash?: string;
  durationMs: number;
  endedAt: number;
}

// Head-to-head player slots with a centered VS divider. When the opponent
// slot is empty (user is alone), we render a pulsing pending circle as
// the obvious "share your code" affordance.
// Memoised so the 1-second idle-warning tick doesn't keep re-mounting the
// emote bubble keys and replaying their float animations.
const PlayersVs = memo(_PlayersVs);
function _PlayersVs({
  me,
  opponent,
  hostClientId,
  emotes,
}: {
  me: PresenceMember | null;
  opponent: PresenceMember | null;
  hostClientId: string | undefined;
  emotes: Record<
    string,
    { primaryUrl: string; fallbackUrl: string; label: string; loopMs: number; key: number }
  >;
}) {
  return (
    <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 sm:gap-4">
      {me ? (
        <PlayerSlot
          member={me}
          isHost={me.clientId === hostClientId}
          isSelf
          emote={emotes[me.clientId] ?? null}
          anchor="left"
        />
      ) : (
        <EmptySlot label="You" side="left" />
      )}

      {/* VS centerpiece — gradient-clip in the site's spring→aqua accent */}
      <div className="flex flex-col items-center select-none px-1">
        <span className="hidden sm:block h-px w-10 bg-gradient-to-r from-transparent via-spring-green-500/30 to-transparent mb-3" />
        <span
          className={`${orbitron.className} text-4xl sm:text-5xl font-black tracking-tight bg-gradient-to-br from-spring-green-300 to-aquamarine-400 bg-clip-text text-transparent`}
          aria-hidden
        >
          VS
        </span>
        <span className="hidden sm:block h-px w-10 bg-gradient-to-r from-transparent via-spring-green-500/30 to-transparent mt-3" />
      </div>

      {opponent ? (
        <PlayerSlot
          member={opponent}
          isHost={opponent.clientId === hostClientId}
          isSelf={false}
          emote={emotes[opponent.clientId] ?? null}
          anchor="right"
        />
      ) : (
        <EmptySlot label="Waiting…" side="right" />
      )}
    </div>
  );
}

function PlayerSlot({
  member,
  isHost,
  isSelf,
  emote,
  anchor,
}: {
  member: PresenceMember;
  isHost: boolean;
  isSelf: boolean;
  emote: { primaryUrl: string; fallbackUrl: string; label: string; loopMs: number; key: number } | null;
  anchor: 'left' | 'right';
}) {
  return (
    <div
      className={`relative rounded-xl border p-5 sm:p-6 flex flex-col items-center gap-3 min-w-0 transition-colors ${
        isSelf
          ? 'border-spring-green-500/40 bg-spring-green-500/[0.04]'
          : 'border-white/[0.10] bg-mirage-900/40'
      }`}
    >
      <div className="relative">
        <PlayerAvatar
          userId={member.clientId}
          displayName={member.data.displayName}
          discordId={member.data.discordId}
          avatarHash={member.data.avatarHash}
          size={80}
          ringClass={
            isSelf
              ? 'ring-2 ring-spring-green-400 ring-offset-2 ring-offset-mirage-950'
              : 'ring-2 ring-white/20 ring-offset-2 ring-offset-mirage-950'
          }
          emote={emote}
          emoteAnchor={anchor}
        />
        {isHost && (
          <span
            className="absolute -top-1.5 -right-1.5 inline-flex items-center justify-center w-5 h-5 rounded-full bg-amber-300 shadow-md shadow-amber-300/30 border border-amber-200"
            title="Host"
            aria-label="Host"
          >
            <Crown className="w-3 h-3 text-amber-900" strokeWidth={2.5} />
          </span>
        )}
        {/* Online dot — bottom right of avatar */}
        <span className="absolute -bottom-0.5 -right-0.5 w-3.5 h-3.5 rounded-full bg-spring-green-400 border-2 border-mirage-950" />
      </div>
      <span
        className={`text-base font-bold truncate max-w-full text-center ${
          isSelf ? 'text-white' : 'text-gray-100'
        }`}
      >
        {member.data.displayName}
      </span>
      <span
        className={`text-[11px] font-mono ${
          isSelf ? 'text-spring-green-400' : 'text-gray-500'
        }`}
      >
        {isSelf ? 'you' : 'opponent'}
      </span>
    </div>
  );
}

function EmptySlot({ label, side }: { label: string; side: 'left' | 'right' }) {
  return (
    <div className="relative rounded-xl border border-dashed border-white/15 bg-white/[0.02] p-5 sm:p-6 flex flex-col items-center gap-3 min-w-0">
      <div className="w-20 h-20 rounded-full bg-white/[0.03] border border-dashed border-white/15 flex items-center justify-center">
        <Loader2 className="w-5 h-5 text-spring-green-400/30 animate-spin" />
      </div>
      <span className="text-gray-400 text-base font-medium truncate max-w-full text-center">
        {label}
      </span>
      <span className="text-[11px] font-mono text-gray-600">
        {side === 'right' ? 'share the code →' : 'open slot'}
      </span>
    </div>
  );
}

const MatchHistoryRow = memo(_MatchHistoryRow);
function _MatchHistoryRow({ entry }: { entry: MatchHistoryEntry }) {
  const gameLabel = ONEV_ONE_GAMES.find((g) => g.id === entry.game)?.label ?? entry.game;
  const isDraw = entry.winnerClientId === null;
  return (
    <li className="flex items-center gap-3 px-3 py-2 rounded-lg bg-white/[0.02]">
      <span className="text-[11px] text-white/45 uppercase tracking-wider w-24 shrink-0 truncate">
        {gameLabel}
      </span>
      <div className="flex items-center gap-2 flex-1 min-w-0">
        {isDraw ? (
          <span className="text-xs text-amber-300/90 font-medium">Draw</span>
        ) : (
          <>
            <PlayerAvatar
              userId={entry.winnerClientId ?? ''}
              displayName={entry.winnerName ?? '?'}
              discordId={entry.winnerDiscordId}
              avatarHash={entry.winnerAvatarHash}
              size={20}
              linkable={!!entry.winnerClientId}
            />
            <span className="text-xs text-white/80 truncate">{entry.winnerName ?? 'Unknown'}</span>
            <span className="text-[10px] uppercase tracking-wider text-[#54FFA4]/80 shrink-0">
              won
            </span>
          </>
        )}
      </div>
      <span className="text-[10px] text-white/35 font-mono tabular-nums shrink-0">
        {(entry.durationMs / 1000).toFixed(1)}s
      </span>
    </li>
  );
}

// Memoised — re-renders only when `onSend` identity changes (it's wrapped
// in useCallback in the parent), not on every emote/presence tick.
const EmoteBar = memo(function EmoteBar({ onSend }: { onSend: (emoteId: string) => void }) {
  return (
    <div className="flex items-center gap-1 rounded-2xl bg-black/70 backdrop-blur-md border border-white/10 p-1.5 shadow-xl shadow-black/40">
      {EMOTES.map((emote) => (
        <button
          key={emote.id}
          type="button"
          onClick={() => onSend(emote.id)}
          title={emote.label}
          aria-label={emote.label}
          className="p-1.5 rounded-xl hover:bg-white/10 transition-colors active:scale-90"
        >
          {/* Picker bar uses the STATIC Noto PNG — animated WebPs sitting
              here at all times were heavy enough to crash some browsers.
              The animated version only fires when an emote is sent. */}
          <EmoteImage
            primaryUrl={emote.staticUrl}
            fallbackUrl={emote.fallbackUrl}
            label={emote.label}
            size={44}
            className="block"
          />
        </button>
      ))}
    </div>
  );
});

function MatchHeader({
  remainingMs,
  onForfeit,
}: {
  remainingMs: number;
  onForfeit: () => void;
}) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  const seconds = Math.max(0, Math.ceil(remainingMs / 1000));
  const mm = Math.floor(seconds / 60);
  const ss = seconds % 60;
  const lowTime = remainingMs <= 30 * 1000;

  return (
    // Sits at the top-center of the viewport. The inner divider lines up with
    // the splitscreen's vertical divider (also at viewport-center), so the
    // pill visually breaks the divider and "carries" it across.
    <div className="fixed top-0 left-1/2 -translate-x-1/2 z-50 pt-3 pointer-events-none">
      <div
        className={`pointer-events-auto grid grid-cols-[5rem_auto_5rem] items-center gap-x-3 rounded-full bg-black/80 backdrop-blur-sm px-4 py-2 border border-white/10 shadow-xl shadow-black/50 transition-all duration-500 ease-out ${
          mounted ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-3'
        }`}
      >
        <span
          className={`text-right text-sm font-mono tabular-nums transition-colors duration-300 ${
            lowTime ? 'text-amber-300' : 'text-white/75'
          }`}
        >
          {mm}:{ss.toString().padStart(2, '0')}
        </span>
        <span className="w-px h-4 bg-white/20" />
        <button
          onClick={onForfeit}
          className="justify-self-start text-sm text-white/60 hover:text-red-300 transition-colors duration-200 inline-flex items-center gap-1.5"
        >
          <LogOut className="w-3.5 h-3.5" />
          Forfeit
        </button>
      </div>
    </div>
  );
}

function OutcomeView({
  iWon,
  isDraw,
  reason,
  game,
  winnerClientId,
  myResult,
  opponentResult,
  me,
  opponent,
  emotes,
  onBack,
}: {
  iWon: boolean;
  isDraw: boolean;
  reason: 'finished' | 'timeout';
  game: GameType;
  winnerClientId: string | null;
  myResult: GameResult | null;
  opponentResult: GameResult | null;
  me: PresenceMember | null;
  opponent: PresenceMember | null;
  emotes: Record<string, { primaryUrl: string; fallbackUrl: string; label: string; loopMs: number; key: number }>;
  onBack: () => void;
}) {
  const gameLabel = ONEV_ONE_GAMES.find((g) => g.id === game)?.label ?? game;
  const title = isDraw ? 'Draw' : iWon ? 'You won' : 'You lost';
  const subtitle = reason === 'timeout'
    ? 'Match timed out'
    : iWon && !myResult
      ? 'Opponent forfeited'
      : 'Match over';
  const glow = isDraw
    ? 'rgba(252, 211, 77, 0.08)'
    : iWon
      ? 'rgba(84, 255, 164, 0.12)'
      : 'rgba(248, 113, 113, 0.05)';

  return (
    <div className="min-h-screen flex items-center justify-center p-4 relative overflow-hidden">
      <div
        aria-hidden
        className="absolute inset-0 pointer-events-none"
        style={{ background: `radial-gradient(circle at center, ${glow} 0%, transparent 55%)` }}
      />

      <div className="relative w-full max-w-md text-center">
        <p className="text-white/30 text-[11px] uppercase tracking-[0.25em] font-medium mb-4 outcome-fade-in">
          {gameLabel} <span className="text-white/15 mx-1.5">·</span> {subtitle}
        </p>

        {iWon && !isDraw && (
          <div className="flex justify-center mb-3 outcome-trophy-in">
            <Trophy className="w-10 h-10 text-amber-300" strokeWidth={1.5} />
          </div>
        )}
        <h2
          className={`text-5xl sm:text-6xl font-bold mb-8 outcome-title-in tracking-tight ${
            isDraw ? 'text-amber-300' : iWon ? '' : 'text-white/80'
          }`}
          style={
            iWon && !isDraw
              ? {
                  color: 'transparent',
                  backgroundImage:
                    'linear-gradient(135deg, #ffffff 0%, #d8fff0 30%, #54FFA4 100%)',
                  WebkitBackgroundClip: 'text',
                  backgroundClip: 'text',
                }
              : undefined
          }
        >
          {title}
        </h2>

        <div className="rounded-2xl bg-white/[0.03] border border-white/[0.06] p-2 mb-6 outcome-card-in">
          {isDraw && reason === 'timeout' && !myResult && !opponentResult ? (
            <p className="text-white/50 text-sm py-4 px-4">
              Neither player finished in time.
            </p>
          ) : (
            <div className="space-y-0.5">
              {/* Skip "You" row when I won by default (opp forfeited before I
                  finished) — title already says I won. */}
              {(myResult || !iWon) && (
                <ResultRow
                  member={me}
                  emote={me ? emotes[me.clientId] ?? null : null}
                  result={myResult}
                  isWinner={!isDraw && me?.clientId === winnerClientId}
                  isSelf
                  fallbackLabel="You"
                />
              )}
              <ResultRow
                member={opponent}
                emote={opponent ? emotes[opponent.clientId] ?? null : null}
                result={opponentResult}
                isWinner={!isDraw && opponent?.clientId === winnerClientId}
                isSelf={false}
                fallbackLabel="Opponent"
              />
            </div>
          )}
        </div>

        <button
          onClick={onBack}
          className="group w-full rounded-2xl bg-white/[0.04] hover:bg-white/[0.08] active:bg-white/[0.06] border border-white/[0.06] hover:border-white/15 text-white/90 py-3.5 font-medium transition-all duration-200 outcome-cta-in inline-flex items-center justify-center gap-2"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
          Back to lobby
        </button>
      </div>

      <style jsx>{`
        .outcome-fade-in {
          animation: outcomeFadeIn 0.5s ease-out 0.05s backwards;
        }
        .outcome-trophy-in {
          animation: outcomeTrophyIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) 0.1s backwards;
        }
        .outcome-title-in {
          animation: outcomeTitleIn 0.55s cubic-bezier(0.16, 1, 0.3, 1) 0.2s backwards;
        }
        .outcome-card-in {
          animation: outcomeFadeIn 0.5s ease-out 0.4s backwards;
        }
        .outcome-cta-in {
          animation: outcomeFadeIn 0.5s ease-out 0.55s backwards;
        }
        @keyframes outcomeFadeIn {
          0% {
            opacity: 0;
            transform: translateY(8px);
          }
          100% {
            opacity: 1;
            transform: translateY(0);
          }
        }
        @keyframes outcomeTrophyIn {
          0% {
            opacity: 0;
            transform: scale(0.5);
          }
          100% {
            opacity: 1;
            transform: scale(1);
          }
        }
        @keyframes outcomeTitleIn {
          0% {
            opacity: 0;
            transform: scale(0.92) translateY(8px);
          }
          100% {
            opacity: 1;
            transform: scale(1) translateY(0);
          }
        }
      `}</style>
    </div>
  );
}

// Pure derivation: given both clients' results + matchExpired + the two
// clientIds, return the canonical { winner, reason }. Both host and the
// non-host fallback call this with identical inputs so they converge.
function deriveWinner(
  myResult: GameResult | null,
  opponentResult: GameResult | null,
  matchExpired: boolean,
  myClientId: string,
  opponentClientId: string,
): { winnerClientId: string | null; reason: 'finished' | 'timeout' } {
  const reason: 'finished' | 'timeout' = matchExpired ? 'timeout' : 'finished';

  if (myResult && opponentResult) {
    if (myResult.won && opponentResult.won) {
      // Race: faster locally-measured time wins; clientId tiebreaks an
      // exact tie so both clients converge on the same winner.
      if (myResult.elapsedMs < opponentResult.elapsedMs) return { winnerClientId: myClientId, reason };
      if (myResult.elapsedMs > opponentResult.elapsedMs) return { winnerClientId: opponentClientId, reason };
      const winner = myClientId < opponentClientId ? myClientId : opponentClientId;
      return { winnerClientId: winner, reason };
    }
    if (myResult.won) return { winnerClientId: myClientId, reason };
    if (opponentResult.won) return { winnerClientId: opponentClientId, reason };
    return { winnerClientId: null, reason }; // both lost
  }

  if (myResult) {
    return { winnerClientId: myResult.won ? myClientId : opponentClientId, reason };
  }
  if (opponentResult) {
    return { winnerClientId: opponentResult.won ? opponentClientId : myClientId, reason };
  }
  // Only matchExpired with no results — true draw.
  return { winnerClientId: null, reason };
}

function ResultRow({
  member,
  emote,
  result,
  isWinner,
  isSelf,
  fallbackLabel,
}: {
  member: PresenceMember | null;
  emote: { primaryUrl: string; fallbackUrl: string; label: string; key: number } | null;
  result: GameResult | null;
  isWinner: boolean;
  isSelf: boolean;
  fallbackLabel: string;
}) {
  return (
    <div
      className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-colors ${
        isWinner ? 'bg-[#54FFA4]/[0.07]' : ''
      }`}
    >
      {member ? (
        <PlayerAvatar
          userId={member.clientId}
          displayName={member.data.displayName}
          discordId={member.data.discordId}
          avatarHash={member.data.avatarHash}
          size={26}
          ringClass={isWinner ? 'ring-2 ring-[#54FFA4]/40' : undefined}
        />
      ) : (
        <div className="w-[26px] h-[26px] rounded-full bg-white/10" />
      )}
      <div className="flex items-center gap-2 flex-1 min-w-0 text-left">
        <span
          className={`text-sm truncate min-w-0 ${isWinner ? 'text-white font-medium' : 'text-white/75'}`}
        >
          {member ? member.data.displayName : fallbackLabel}
        </span>
        {isSelf && (
          <span className="text-[9px] uppercase tracking-wider text-white/30 shrink-0">you</span>
        )}
        {emote && (
          <InlineEmote
            primaryUrl={emote.primaryUrl}
            fallbackUrl={emote.fallbackUrl}
            label={emote.label}
            emoteKey={emote.key}
          />
        )}
      </div>
      {result ? (
        <div className="flex items-center gap-2.5 shrink-0">
          <span className="text-[11px] text-white/40 uppercase tracking-wider tabular-nums">
            {result.score}pts
          </span>
          <span
            className={`text-sm font-mono tabular-nums ${isWinner ? 'text-[#54FFA4]' : 'text-white/65'}`}
          >
            {(result.elapsedMs / 1000).toFixed(1)}s
          </span>
          {isWinner && <Trophy className="w-3.5 h-3.5 text-amber-300" strokeWidth={2} />}
        </div>
      ) : (
        <span className="text-xs text-white/35 italic shrink-0">didn&apos;t finish</span>
      )}
    </div>
  );
}

function InlineEmote({
  primaryUrl,
  fallbackUrl,
  label,
  emoteKey,
}: {
  primaryUrl: string;
  fallbackUrl: string;
  label: string;
  emoteKey: number;
}) {
  return (
    <span
      key={emoteKey}
      className="emote-inline inline-flex items-center justify-center w-8 h-8 rounded-full bg-white/[0.05] border border-white/15 shrink-0"
    >
      <EmoteImage primaryUrl={primaryUrl} fallbackUrl={fallbackUrl} label={label} size={26} />
    </span>
  );
}

export function Countdown({ remainingMs }: { remainingMs: number }) {
  const seconds = Math.max(1, Math.ceil(remainingMs / 1000));
  return (
    <div
      className="min-h-screen flex items-center justify-center relative overflow-hidden"
      style={{ perspective: '1200px' }}
    >
      {/* Soft radial backdrop so the number sits in a faint pool of green light. */}
      <div
        aria-hidden
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(circle at center, rgba(84,255,164,0.10) 0%, rgba(84,255,164,0.04) 25%, transparent 55%)',
        }}
      />
      {/* Faint horizon line that the number lands on. */}
      <div
        aria-hidden
        className="absolute left-1/2 top-1/2 -translate-x-1/2 w-[36rem] h-px pointer-events-none"
        style={{
          background:
            'linear-gradient(to right, transparent, rgba(84,255,164,0.4), transparent)',
        }}
      />
      <div
        key={seconds}
        className={`${orbitron.className} relative text-[12rem] sm:text-[18rem] leading-none tabular-nums select-none countdown-num`}
        style={{
          color: 'transparent',
          backgroundImage:
            'linear-gradient(135deg, #ffffff 0%, #d8fff0 35%, #54FFA4 65%, #2db97a 100%)',
          WebkitBackgroundClip: 'text',
          backgroundClip: 'text',
          letterSpacing: '-0.04em',
        }}
      >
        {seconds}
      </div>
      <style jsx>{`
        .countdown-num {
          animation: rush 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;
          transform-origin: center;
        }
        @keyframes rush {
          0% {
            transform: scale(0.15) translateZ(-600px);
            opacity: 0;
            filter: blur(40px)
              drop-shadow(0 0 0 rgba(84, 255, 164, 0));
          }
          30% {
            transform: scale(1.3) translateZ(0);
            opacity: 1;
            filter: blur(0)
              drop-shadow(0 0 90px rgba(84, 255, 164, 0.7))
              drop-shadow(0 0 30px rgba(255, 255, 255, 0.4));
          }
          100% {
            transform: scale(1) translateZ(0);
            opacity: 0.95;
            filter: blur(0)
              drop-shadow(0 0 60px rgba(84, 255, 164, 0.5))
              drop-shadow(0 0 20px rgba(255, 255, 255, 0.25));
          }
        }
      `}</style>
    </div>
  );
}

// Host control. Two distinct jobs, cleanly separated:
//   - Alone:      set lobby visibility (Private vs Public). Public also
//                 needs a game to list the lobby under on /lobby.
//   - 2 players:  pick a game to start the match.
function GamePicker({
  isAlone,
  publishGame,
  onPublishChange,
  onStart,
  focusMode,
  onFocusModeChange,
  loggedIn,
}: {
  isAlone: boolean;
  publishGame: GameType | null;
  onPublishChange: (next: GameType | null) => void;
  onStart: (game: GameType) => void;
  focusMode: boolean;
  onFocusModeChange: (next: boolean) => void;
  loggedIn: boolean;
}) {
  if (isAlone) {
    return (
      <VisibilityControl
        publishGame={publishGame}
        onPublishChange={onPublishChange}
        loggedIn={loggedIn}
      />
    );
  }

  return (
    <section>
      <div className="flex items-center justify-between gap-3 mb-4">
        <h2 className="text-lg font-semibold text-white">Pick a game to start</h2>
        <FocusToggle enabled={focusMode} onChange={onFocusModeChange} />
      </div>
      <div className="flex flex-wrap justify-center gap-3">
        {ONEV_ONE_GAMES.map((entry) => (
          <GameTile
            key={entry.id}
            gameId={entry.id}
            label={entry.label}
            mode="start"
            selected={false}
            onClick={() => onStart(entry.id)}
          />
        ))}
      </div>
    </section>
  );
}

// Visibility — explicit Private/Public switch. Private (publishGame=null)
// means code-only; Public lists the lobby on /lobby under a chosen game.
function VisibilityControl({
  publishGame,
  onPublishChange,
  loggedIn,
}: {
  publishGame: GameType | null;
  onPublishChange: (next: GameType | null) => void;
  loggedIn: boolean;
}) {
  const isPublic = publishGame !== null;
  // Switching to public needs a game to list under; default to the first.
  const goPublic = () => onPublishChange(publishGame ?? ONEV_ONE_GAMES[0].id);

  return (
    <section>
      <h2 className="text-lg font-semibold text-white mb-1">
        Waiting for an opponent
      </h2>
      <p className="text-gray-400 text-sm mb-5">
        Share your code, or open the lobby to anyone. The game is picked once
        someone joins.
      </p>

      {/* Private / Public segmented switch */}
      <div className="grid grid-cols-2 gap-1 p-1 rounded-lg bg-mirage-950/60 border border-white/10">
        <button
          type="button"
          onClick={() => onPublishChange(null)}
          className={`flex items-center justify-center gap-2 rounded-md py-2.5 text-sm font-medium transition-colors ${
            !isPublic
              ? 'bg-spring-green-500 text-mirage-950'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          <Lock className="w-4 h-4" />
          Private
        </button>
        <button
          type="button"
          onClick={goPublic}
          disabled={!loggedIn}
          className={`flex items-center justify-center gap-2 rounded-md py-2.5 text-sm font-medium transition-colors disabled:cursor-not-allowed ${
            isPublic
              ? 'bg-spring-green-500 text-mirage-950'
              : 'text-gray-400 hover:text-white disabled:opacity-40 disabled:hover:text-gray-400'
          }`}
        >
          <Globe className="w-4 h-4" />
          Public
        </button>
      </div>

      {!loggedIn && (
        <p className="text-gray-500 text-xs mt-3">
          Log in to list your lobby publicly.
        </p>
      )}

      {/* When public, choose which game the listing shows under. */}
      {isPublic && (
        <div className="mt-6">
          <h3 className="text-sm font-medium text-gray-300 mb-3 text-center">
            Listed under
          </h3>
          <div className="flex flex-wrap justify-center gap-3">
            {ONEV_ONE_GAMES.map((entry) => (
              <GameTile
                key={entry.id}
                gameId={entry.id}
                label={entry.label}
                mode="select"
                selected={publishGame === entry.id}
                onClick={() => onPublishChange(entry.id)}
              />
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

/* Game thumbnail tile. mode 'start' shows a Start overlay on hover;
   mode 'select' shows a check when chosen. */
function GameTile({
  gameId,
  label,
  mode,
  selected,
  onClick,
}: {
  gameId: GameType;
  label: string;
  mode: 'start' | 'select';
  selected: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={label}
      className={`group relative w-36 sm:w-40 overflow-hidden rounded-lg flex flex-col text-left transition-all duration-200 active:scale-[0.98] ${
        selected
          ? 'bg-spring-green-500/10 border-2 border-spring-green-400'
          : 'bg-mirage-900/50 border border-white/10 hover:border-spring-green-400/50 hover:-translate-y-0.5'
      }`}
    >
      <div className="relative aspect-[4/3] flex items-center justify-center p-3">
        <Image
          src={GAME_THUMB[gameId]}
          alt={label}
          width={240}
          height={180}
          className="relative w-full h-full object-contain transition-transform duration-200 group-hover:scale-105 [filter:drop-shadow(0_4px_10px_rgba(0,0,0,0.4))]"
          unoptimized
        />
        {selected && (
          <span className="absolute top-2 right-2 inline-flex items-center justify-center w-5 h-5 rounded-full bg-spring-green-500 text-mirage-950">
            <Check className="w-3 h-3" strokeWidth={3} />
          </span>
        )}
        {mode === 'start' && (
          <span className="absolute inset-0 flex items-center justify-center bg-mirage-950/0 group-hover:bg-mirage-950/40 transition-colors duration-200 opacity-0 group-hover:opacity-100">
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-spring-green-500 text-mirage-950 text-sm font-semibold shadow-lg">
              <Play className="w-3.5 h-3.5" fill="currentColor" strokeWidth={0} />
              Start
            </span>
          </span>
        )}
      </div>
      <div className="px-3 py-2.5 border-t border-white/10">
        <span
          className={`text-sm font-medium truncate inline-block max-w-full ${
            selected ? 'text-spring-green-300' : 'text-gray-200'
          }`}
        >
          {label}
        </span>
      </div>
    </button>
  );
}

function FocusToggle({
  enabled,
  onChange,
}: {
  enabled: boolean;
  onChange: (next: boolean) => void;
}) {
  return (
    <div className="inline-flex items-center gap-2">
      <span className="group/info relative inline-flex items-center text-white/35 hover:text-white/65 cursor-help">
        <Info className="w-3.5 h-3.5" />
        <span className="pointer-events-none absolute top-full right-0 mt-2 w-56 px-3 py-2 rounded-lg bg-black/90 backdrop-blur border border-white/10 text-white/80 text-[11px] leading-snug shadow-xl opacity-0 group-hover/info:opacity-100 transition-opacity z-50">
          Focus mode hides your opponent&apos;s board and shows a compact
          progress widget in the corner instead.
        </span>
      </span>
      <label className="inline-flex items-center gap-2 text-xs text-white/65 cursor-pointer select-none">
        <span className="font-medium">Focus mode</span>
        <button
          type="button"
          role="switch"
          aria-checked={enabled}
          onClick={() => onChange(!enabled)}
          className={`relative inline-block w-10 h-6 rounded-full transition-colors ${
            enabled
              ? 'bg-spring-green-300 shadow-inner shadow-spring-green-500/40'
              : 'bg-white/10 hover:bg-white/15'
          }`}
        >
          <span
            className={`absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white shadow-md shadow-black/30 transition-transform ${
              enabled ? 'translate-x-4' : 'translate-x-0'
            }`}
          />
        </button>
      </label>
    </div>
  );
}

function ConnectionStatus({ status }: { status: ChannelStatus }) {
  if (status === 'connected') {
    return (
      <span className="inline-flex items-center gap-1.5 text-xs text-white/50">
        <span className="w-1.5 h-1.5 rounded-full bg-[#54FFA4]" />
        Live
      </span>
    );
  }
  if (status === 'failed') {
    return <span className="text-xs text-red-400/80">Disconnected</span>;
  }
  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-white/40">
      <Loader2 className="w-3 h-3 animate-spin" />
      Connecting
    </span>
  );
}
